from apps.models import (
    Property, User, City, Region, District, Metro,
    Category, ResidentialComplex, Amenity, Country
)
from django.utils import timezone
import random
from decimal import Decimal

# Fetch necessary related objects
users = list(User.objects.all())
cities = list(City.objects.all())
regions = list(Region.objects.all())
districts = list(District.objects.all())
metros = list(Metro.objects.all())
categories = list(Category.objects.all())
residential_complexes = list(ResidentialComplex.objects.all())
amenities = list(Amenity.objects.all())
country = Country.objects.get(name='Uzbekistan')

# Sample data for properties
property_data = [
    {
        "name": "Modern Apartment in Chilonzor",
        "address": "123 Chilonzor Street",
        "building_material": Property.Material.BRICK,
        "renovation_needed": Property.Renovation.EURO,
        "area": Decimal("85.5"),
        "room": 3,
        "floor": 5,
        "price": Decimal("85000"),
        "description": "A spacious and modern apartment located in the heart of Chilonzor.",
        "type": Property.Type.SALE,
        "label": Property.Label.PREMIUM,
        "residential_type": Property.ResidentialType.FINISHED,
        "commissioning_date": timezone.now().date(),
        "views": 120,
        "saves": 15,
        "latitude": Decimal("41.2995"),
        "longitude": Decimal("69.2401"),
    },
    {
        "name": "Cozy Flat near Kosmonavtlar Metro",
        "address": "45 Space Avenue",
        "building_material": Property.Material.CONCRETE,
        "renovation_needed": Property.Renovation.MID,
        "area": Decimal("60.0"),
        "room": 2,
        "floor": 3,
        "price": Decimal("60000"),
        "description": "Comfortable flat with easy access to Kosmonavtlar Metro station.",
        "type": Property.Type.RENT,
        "label": Property.Label.VIP,
        "residential_type": Property.ResidentialType.ON_TIME,
        "commissioning_date": timezone.now().date(),
        "views": 200,
        "saves": 30,
        "latitude": Decimal("41.3111"),
        "longitude": Decimal("69.2797"),
    },
    {
        "name": "Luxury Apartment in Yunusobod",
        "address": "8 Silk Road Avenue",
        "building_material": Property.Material.MONOLITHIC,
        "renovation_needed": Property.Renovation.EURO,
        "area": Decimal("120.0"),
        "room": 4,
        "floor": 7,
        "price": Decimal("150000"),
        "description": "Spacious luxury apartment in a high-rise with great city views.",
        "type": Property.Type.SALE,
        "label": Property.Label.PREMIUM,
        "residential_type": Property.ResidentialType.FINISHED,
        "commissioning_date": timezone.now().date(),
        "views": 450,
        "saves": 60,
        "latitude": Decimal("41.3500"),
        "longitude": Decimal("69.2900"),
    },
    {
        "name": "Affordable Home in Sergeli",
        "address": "22 Tinchlik Street",
        "building_material": Property.Material.CONCRETE_BLOCKS,
        "renovation_needed": Property.Renovation.REQUIRED,
        "area": Decimal("45.0"),
        "room": 2,
        "floor": 1,
        "price": Decimal("32000"),
        "description": "Good starter home in a quiet district, needs minor renovation.",
        "type": Property.Type.SALE,
        "label": Property.Label.URGENT,
        "residential_type": Property.ResidentialType.ON_TIME,
        "commissioning_date": timezone.now().date(),
        "views": 140,
        "saves": 20,
        "latitude": Decimal("41.2635"),
        "longitude": Decimal("69.1802"),
    },
    {
        "name": "Stylish Loft near Mustaqillik Square",
        "address": "10 Independence Blvd",
        "building_material": Property.Material.BRICK,
        "renovation_needed": Property.Renovation.AUTHOR,
        "area": Decimal("95.0"),
        "room": 3,
        "floor": 5,
        "price": Decimal("98000"),
        "description": "Designer loft with open space layout and premium furnishings.",
        "type": Property.Type.SALE,
        "label": Property.Label.VIP,
        "residential_type": Property.ResidentialType.FREE_LAYOUT,
        "commissioning_date": timezone.now().date(),
        "views": 310,
        "saves": 45,
        "latitude": Decimal("41.3120"),
        "longitude": Decimal("69.2780"),
    },
    {
        "name": "Bright Flat in Mirzo Ulugbek District",
        "address": "33 Astronomers Avenue",
        "building_material": Property.Material.CONCRETE,
        "renovation_needed": Property.Renovation.MID,
        "area": Decimal("70.0"),
        "room": 3,
        "floor": 6,
        "price": Decimal("70000"),
        "description": "A well-lit apartment perfect for families near schools and shops.",
        "type": Property.Type.SALE,
        "label": Property.Label.PREMIUM,
        "residential_type": Property.ResidentialType.ON_TIME,
        "commissioning_date": timezone.now().date(),
        "views": 260,
        "saves": 35,
        "latitude": Decimal("41.3150"),
        "longitude": Decimal("69.3050"),
    },
    {
        "name": "Modern Studio near Buyuk Ipak Yuli",
        "address": "19 Metro Lane",
        "building_material": Property.Material.MONOLITHIC,
        "renovation_needed": Property.Renovation.EURO,
        "area": Decimal("35.0"),
        "room": 1,
        "floor": 2,
        "price": Decimal("40000"),
        "description": "Compact and efficient studio ideal for students and expats.",
        "type": Property.Type.RENT,
        "label": Property.Label.URGENT,
        "residential_type": Property.ResidentialType.FINISHED,
        "commissioning_date": timezone.now().date(),
        "views": 180,
        "saves": 25,
        "latitude": Decimal("41.3330"),
        "longitude": Decimal("69.3000"),
    },
    {
        "name": "Green Park View Residence",
        "address": "77 Navoi Street",
        "building_material": Property.Material.ANOTHER,
        "renovation_needed": Property.Renovation.BLACK_PLASTER,
        "area": Decimal("110.0"),
        "room": 4,
        "floor": 8,
        "price": Decimal("115000"),
        "description": "Newly built apartment with a beautiful view of the city park.",
        "type": Property.Type.SALE,
        "label": Property.Label.PREMIUM,
        "residential_type": Property.ResidentialType.FREE_LAYOUT,
        "commissioning_date": timezone.now().date(),
        "views": 380,
        "saves": 40,
        "latitude": Decimal("41.3200"),
        "longitude": Decimal("69.2600"),
    },
    {
        "name": "Compact Apartment in Yakkasaray",
        "address": "15 Almazar Street",
        "building_material": Property.Material.CONCRETE_BLOCKS,
        "renovation_needed": Property.Renovation.REQUIRED,
        "area": Decimal("55.0"),
        "room": 2,
        "floor": 4,
        "price": Decimal("50000"),
        "description": "Affordable option in central location, ideal for small families.",
        "type": Property.Type.RENT,
        "label": Property.Label.URGENT,
        "residential_type": Property.ResidentialType.ON_TIME,
        "commissioning_date": timezone.now().date(),
        "views": 150,
        "saves": 18,
        "latitude": Decimal("41.2960"),
        "longitude": Decimal("69.2700"),
    },
    {
        "name": "Business Class Flat in Olmazor",
        "address": "5 Business Tower",
        "building_material": Property.Material.CONCRETE,
        "renovation_needed": Property.Renovation.AUTHOR,
        "area": Decimal("100.0"),
        "room": 3,
        "floor": 10,
        "price": Decimal("130000"),
        "description": "High-class property with smart home features and security.",
        "type": Property.Type.SALE,
        "label": Property.Label.VIP,
        "residential_type": Property.ResidentialType.FINISHED,
        "commissioning_date": timezone.now().date(),
        "views": 420,
        "saves": 50,
        "latitude": Decimal("41.2780"),
        "longitude": Decimal("69.2500"),
    },

]

# Function to create properties
for data in property_data:
    property_instance = Property.objects.create(
        name=data["name"],
        address=data["address"],
        building_material=data["building_material"],
        renovation_needed=data["renovation_needed"],
        area=data["area"],
        room=data["room"],
        floor=data["floor"],
        price=data["price"],
        description=data["description"],
        type=data["type"],
        category=random.choice(categories),
        label=data["label"],
        residential_complex=random.choice(residential_complexes),
        residential_type=data["residential_type"],
        commissioning_date=data["commissioning_date"],
        views=data["views"],
        saves=data["saves"],
        city=random.choice(cities),
        region=random.choice(regions),
        metro=random.choice(metros),
        district=random.choice(districts),
        country=country,
        user=random.choice(users),
        latitude=data["latitude"],
        longitude=data["longitude"],
        status=Property.Status.ACTIVE,
    )
    # Assign random amenities
    selected_amenities = random.sample(amenities, k=min(3, len(amenities)))
    property_instance.amenities.set(selected_amenities)
    property_instance.save()
