# Generated by Django 5.2 on 2025-05-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_tariff'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='label',
            field=models.CharField(blank=True, choices=[('vip', 'VIP'), ('premium', 'Premium'), ('urgent', 'Urgent')], max_length=10, null=True),
        ),
    ]
