# Generated by Django 5.2 on 2025-05-09 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_phoneverification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='from_user',
            new_name='sender',
        ),
    ]
