# Generated by Django 5.2 on 2025-05-09 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_rename_from_user_message_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='text',
            new_name='message',
        ),
    ]
