# Generated by Django 5.2 on 2025-05-09 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_rename_text_message_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='receiver',
        ),
    ]
