# Generated by Django 5.2 on 2025-05-09 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_rename_user_message_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to=settings.AUTH_USER_MODEL),
        ),
    ]
