# Generated by Django 5.2 on 2025-05-12 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_property_repair'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
