# Generated by Django 5.2 on 2025-05-12 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_alter_amenity_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
